### ISSUE TITLE
Test HotButton control (requires device that has this feature enabled)

### ISSUE THREAD

**Issue by rudybrian** [rudybrian/PyNavienSmartControl#14]
Testing needed to ensure the on-demand functions behave as expected with devices that have this feature enabled.

**Comment by matkam** [comment]
It doesn't seem to work with my heater with external circulation and hot button enabled. The hot button does work in the mobile app.

```
Channel Info
---------------------------
Channel:1
        Device Model Type: NPE2
        Device Count: 1
        Temp Flag: FAHRENHEIT
        Minimum Setting Water Temperature: 97
        Maximum Setting Water Temperature: 185
        Heating Minimum Setting Water Temperature: 32
        Heating Maximum Setting Water Temperature: 32
        Use On Demand: ON
        Heating Control: SUPPLY
        wwsdFlag: OK
        commercialLock: OK
        hotwaterPossibility: OFF
        recirculationPossibility: OFF
        High Temperature: TEMPERATURE_60
        Use Warm Water: ON

...

Channel 1 Info:
Device: 1
State
---------------------------
Controller Version: 11
Panel Version: 19
Device Model Type: NPE2
Device Count: 1
Current Channel: 1
Device Number: 1
Error Code: Normal
Operation Device Number: 1
Average Calorimeter: 24.0 %
Current Gas Usage: 48310.4 BTU
Total Gas Usage: 4170.7 ft³
Hot Water Setting Temperature: 120 °F
Hot Water Current Temperature: 120 °F
Hot Water Flow Rate: 2.7 GPM
Inlet Temperature: 100 °F
Power Status: ON
Heat Status: OFF
Use On Demand: ON
Weekly Control: OFF

# python3 python/NavienSmartControl-CLI.py -channel 1 -devicenumber 1 -ondemand
--------------
Navien-API V1.0
--------------

Traceback (most recent call last):
  File "python/NavienSmartControl-CLI.py", line 484, in <module>
    stateData = navienSmartControl.sendOnDemandControlRequest(
  File "/homebridge/misc/PyNavienSmartControl/python/shared/NavienSmartControl.py", line 1783, in sendOnDemandControlRequest
    raise Exception("Error: Recirculation is disabled.")
Exception: Error: Recirculation is disabled.
```

**Comment by nikshriv** [comment]
I've been working on a Home Assistant integration using this api, and I have found that the "useOnDemand" key in channelInfo is the right indicator of whether external recirculation is available. It has to be ON (value == 1). I'm not sure what the RecirculationFlag is for, but it doesn't work as expected.

Please take a look here:

https://github.com/nikshriv/hass_navien_water_heater/issues/5
